### ISSUE TITLE
quantile.default(cum_est,K) NAN error in kubinek_daily_update.Rmd

### ISSUE THREAD

**Issue by Tsardoz** [saudiwin/corona_tscs#10]
Error in quantile.default(cum_est, 0.5) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE

I think there are 6 occurrences of this
I changed to quantile.default(cum_est, K, na.rm = T) not sure if correct

**Comment by saudiwin** [comment]
the file you should be using is `kubinec_model_preprint.Rmd` (see the README file). The others are old files no longer up to date.
