### ISSUE TITLE
missing suppress_effect in kubinec_model_draft.Rmd

### ISSUE THREAD

**Issue by Tsardoz** [saudiwin/corona_tscs#11]
mcmc_hist(as.array(pan_model_est,c("suppress_effect[1]","suppress_effect[2]")))
Error in check_pars(allpars, pars) : 
  no parameter suppress_effect[1], suppress_effect[2]

**Comment by saudiwin** [comment]
the file you should be using is `kubinec_model_preprint.Rmd` (see the README file). The others are old files no longer up to date.
