### ISSUE TITLE
Records with type "Restriction of Non-Essential Businesses"

### ISSUE THREAD

**Issue by ingonader** [saudiwin/corona_tscs#18]
Most business-related policies are of `type=="Restriction and Regulation of Businesses"`. However, there are two policies with a separate `type`, namely `"Restriction of Non-Essential Businesses"`. It seems as these should be categorized under the former `type`, in the corresponding subcategory.

The `record_id`s of these entries are: 7053515NA, 8819062NA.

**Comment by timothymodel** [comment]
Should be corrected in the most recent data releases
