### ISSUE TITLE
Records with update_type == "End of Policy" with missing end date

### ISSUE THREAD

**Issue by ingonader** [saudiwin/corona_tscs#20]
In the dataset downloaded on 29 Jun 2020, 152 records are classified as `update_type == "End of Policy"`, but they are missing an `date_end`.

The `record_id`s of these records are:
```
"1133827", "1181795", "1328313", "1375594", "1375594", "1375594", "1375594", "1392693", "1410115", "1569199", "1603220", "1603220", "1603220", "1708769", "1926832", "2227511", "2227511", "2227511", "2227511", "2250810", "2369701", "2369701", "2619354", "2675008", "2690257", "286117", "2909273", "3009975", "3009975", "3009975", "301596", "3035427", "30685", "3093940", "3101600", "3101600", "3149249", "3152379", "3262259", "334726", "3600847", "3669312", "3853878", "3990939", "4326634", "4326634", "4326634", "4527866", "4556417", "4556417", "4586988", "4654378", "4668155", "5191563", "5198253", "5343355", "5441699", "5443319", "5508395", "5578470", "5630917", "5768778", "5774249", "5844897", "5914518", "5977", "6011868", "6063948", "6066505", "6066505", "6066505", "6098490", "6150569", "6196547", "624369", "6339986", "6352649", "6352649", "6352649", "6437718", "6448938", "6572275", "6602530", "6674031", "6848661", "6848661", "6942114", "6985001", "7020456", "7035507", "7035507", "7080317", "7080317", "7080317", "7080317", "7155938", "7169024", "7169024", "737153", "7430670", "7530978", "7537257", "7537257", "7537257", "7537257", "7580975", "7628872", "7636521", "7636521", "7712369", "7860415", "7945145", "7977385", "8097838", "8176000", "8176000", "819048", "8222127", "827674", "8301094", "8301094", "8301094", "8301094", "8398739", "8574036", "8628804", "8772657", "8793386", "8822455", "9044740", "9048579", "9134785", "9184664", "9213970", "9248052", "9637060", "9797937", "981700", "9835701", "9850870", "9850870", "9850870", "985255", "9862393", "9862393", "9862393", "9862393", "9862393", "990744", "990744", "990744", "9931248"
```

For some, it seems as if the date that is recorded in the `date_start` column is actually the date that the policy ended (according to the `event_description`). Example:

record_id | policy_id | country | date_announced | date_start | date_end | entry_type | update_type | type | type_sub_cat
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
1133827Em | 1133827 | Austria | 2020-04-21 | 2020-03-23 |   | update | End of Policy | Quarantine | Self-Quarantine (i.e. quarantine at home)

With event description: 
"
Being issolated since March 13, since April 23 those quarantine restrictions are lifted for the towns of Paznaun Ischgl, Galtür, Kappl and See as well as the municipality of St. Anton am Arlberg.
"

**Comment by IsaacBravo** [comment]
Hi, sorry for the late reply, but it is possible to find this combination when updating a policy, as the end date is not directly related to the variable "update_type", but it is related to aspects such as those indicated in this presentation: https://drive.google.com/file/d/13bRZ67rHMV5Fv2UTxI6ZtSz2qu1xxeEF/view
