### ISSUE TITLE
Maybe a typo error in coronanet_release

### ISSUE THREAD

**Issue by 0oshowero0** [saudiwin/corona_tscs#22]
I notice that for record_id=R_1gdyC25xLGlP5H1Bv, the date of the policy may be wrong. The date_start and date_end are both 2024/5/29, and it seems strange. Is that correct?

![image](https://user-images.githubusercontent.com/21094960/90366949-9e154180-e09a-11ea-9993-1837d8c25365.png)

**Comment by saudiwin** [comment]
Thanks! We'll work to correct that @cindyyawencheng

**Comment by IsaacBravo** [comment]
Hi, thank you very much for pointing this out, we will contact the Country Manager to update this situation.
