### ISSUE TITLE
typo in record R_29oBci4H213aoc6NA

### ISSUE THREAD

**Issue by dlusseau** [saudiwin/corona_tscs#24]
Hi,
there is a typo in record_id="R_29oBci4H213aoc6NA"
the announcement date is 2020-03-27
the date_start is 2020-07-28
and the date_end is 2020-04-12

date_start should read 2020-03-28

**Comment by aapetrova** [comment]
Hi David,

Thank you very much for bringing it up! We have added a correction with record id R_1QhezHCMmr0v8YFCj to [the newest release](https://github.com/saudiwin/corona_tscs/blob/master/data/CoronaNet/data_country/coronanet_release/coronanet_release_United%20Kingdom.csv).
