### ISSUE TITLE
Missing Border Closure for Belgium

### ISSUE THREAD

**Issue by dominikobeth** [saudiwin/corona_tscs#25]
Border closure from March 20 
https://www.vrt.be/vrtnws/en/2020/03/20/borders-closed-to-non-essential-travel/
Belgium seems in general to have some missing entries for Border restrictions since only policy one is coded (CoronaNet version from mid october)

**Comment by IsaacBravo** [comment]
Hi, thank you for pointing this out. This issue has been updated and the records incorporated into the CoronaNet dataset.
