### ISSUE TITLE
Missing "Hard" Border closure in Botswana

### ISSUE THREAD

**Issue by dominikobeth** [saudiwin/corona_tscs#26]
Border closure form March 24 
https://www.voanews.com/science-health/coronavirus-outbreak/botswana-no-covid-19-cases-closes-borders-after-death-zimbabwe
I used data from Mid october so one would have to check whether it has been coded since.

**Comment by IsaacBravo** [comment]
Hi, thank you very much for pointing this out, this record has been incorporated into the Data Integration Process spreadsheets, so in the next few weeks, it should be incorporated into the CoronaNet dataset.
