### ISSUE TITLE
Missing Border Closure in Iceland

### ISSUE THREAD

**Issue by dominikobeth** [saudiwin/corona_tscs#27]
"As of 20 March 2020, foreign nationals - except EU/EEA, EFTA or UK nationals - are not allowed to enter Iceland." https://www.icetra.is/about/about/covid-10-info-page/iceland-implements-schengen-and-eu-travel-restrictions

Here, I am not sure whether this falls under an EU policy because Iceland just implemented it but to be sure I raised the issue

**Comment by IsaacBravo** [comment]
Hi, thank you very much for pointing this out, I have just checked the record of this policy, and it is perfect according to the Government's statement.
