### ISSUE TITLE
Missing "Hard" Border Closure policy in Lithuania

### ISSUE THREAD

**Issue by dominikobeth** [saudiwin/corona_tscs#28]
("hard")border Restrictions from March 14 
https://web.archive.org/web/20200621114846/https://www.lrt.lt/en/news-in-english/19/1151413/lithuania-reintroduces-border-controls-considers-barring-entry-to-foreigners 
I used data from Mid october so one would have to check whether it has been coded since.

**Comment by IsaacBravo** [comment]
Hi, thank you very much for pointing this out, this record has been incorporated into the Data Integration Process spreadsheets, so in the next few weeks, it should be incorporated into the CoronaNet dataset.
