### ISSUE TITLE
Missing Border Closure North Korea

### ISSUE THREAD

**Issue by dominikobeth** [saudiwin/corona_tscs#29]
Border closure for tourists/ China on January 21 https://www.nytimes.com/2020/01/21/world/asia/coronavirus-china-north-korea-tourism-ban.html

I used data from Mid october so one would have to check whether it has been coded since.

**Comment by IsaacBravo** [comment]
Hi, thank you very much for pointing this out, this record has been incorporated into the Data Integration Process spreadsheets, so in the next few weeks, it should be incorporated into the CoronaNet dataset.
