### ISSUE TITLE
Missing Border Closure Norway

### ISSUE THREAD

**Issue by dominikobeth** [saudiwin/corona_tscs#30]
Hard border restrictions introduced on March 15   (https://www.regjeringen.no/en/aktuelt/stricter-border-controls-being-introduced/id2693624/)

I used data from mid october so one would have to check whether it is still not coded

**Comment by IsaacBravo** [comment]
Hi, thank you very much for pointing this out, this record has been incorporated into the Data Integration Process spreadsheets, so in the next few weeks, it should be incorporated into the CoronaNet dataset.
