### ISSUE TITLE
Missing Border Closure Côte d'Ivoire

### ISSUE THREAD

**Issue by dominikobeth** [saudiwin/corona_tscs#31]
On March 20, the Government of Cote d’Ivoire announced that the land, aviation and maritime borders will close on midnight, Sunday March 22 for an indeterminate period of time.  Cargo shipments will not be affected.  

https://www.osac.gov/Content/Report/4172acc0-6da9-4dfd-9cbd-1840eb002ff7

In general, no Border Restrictions have been coded for Côte d'Ivoire (version from mid october)

**Comment by IsaacBravo** [comment]
Hi, thank you very much for pointing this out, this record has been incorporated into the Data Integration Process spreadsheets, so in the next few weeks, it should be incorporated into the CoronaNet dataset.
