### ISSUE TITLE
Missing Border Closure policy São Tome and Principe

### ISSUE THREAD

**Issue by dominikobeth** [saudiwin/corona_tscs#32]
https://macauhub.com.mo/2020/03/05/pt-sao-tome-e-principe-acompanha-angola-e-proibe-entrada-de-cidadaos-da-china-e-de-outros-paises-afectados-pelo-covid-19/

The Council of Ministers of São Tomé and Príncipe has decided to prohibit the entry into the country of citizens from China, South Korea, Italy, Iran, Nigeria, Algeria and Senegal as a way of preventing the spread of the new coronavirus (Covid-19), according to an official announcement made on Wednesday [March 4] in São Tomé.

**Comment by IsaacBravo** [comment]
Hi, thank you very much for pointing this out, this record has been incorporated into the Data Integration Process spreadsheets, so in the next few weeks, it should be incorporated into the CoronaNet dataset.
