### ISSUE TITLE
Missing Border Closure Libya

### ISSUE THREAD

**Issue by dominikobeth** [saudiwin/corona_tscs#33]
The Libyan Government of National Accord (GNA) announced a state of emergency beginning March 14, to include the closure of schools and universities until March 30, the closure of Libya’s land and sea borders, and the cessation of all international flights through April 6.  Flying ambulances, air shipping, official delegations returning from abroad, and local flights are still permitted at this time.

https://www.osac.gov/Country/Libya/Content/Detail/Report/0f9f03c0-f787-48d9-a951-1838a3cb46db

**Comment by IsaacBravo** [comment]
Hi, thank you very much for pointing this out, this record has been incorporated into the Data Integration Process spreadsheets, so in the next few weeks, it should be incorporated into the CoronaNet dataset.
