### ISSUE TITLE
Missing Border Closure Mauritius 

### ISSUE THREAD

**Issue by dominikobeth** [saudiwin/corona_tscs#34]
Mauritius is the latest country to close its borders to all foreign nationals, including South Africans. It will come into effect from Thursday, March 19. 

https://www.iol.co.za/travel/africa/covid-19-mauritius-closes-borders-to-all-foreign-nationals-including-south-africans-45190413

https://www.airmauritius.com/news/additional-travel-restrictions-issued-by-the-authorities-in-mauritius

**Comment by IsaacBravo** [comment]
Hi, thank you very much for pointing this out, this record has been incorporated into the Data Integration Process spreadsheets, so in the next few weeks, it should be incorporated into the CoronaNet dataset.
