### ISSUE TITLE
Merge texts in data

### ISSUE THREAD

**Issue by AlexHTW** [saudiwin/corona_tscs#35]
After the latest update of the [Germany dataset ](https://raw.githubusercontent.com/saudiwin/corona_tscs/master/data/CoronaNet/data_country/coronanet_release/coronanet_release_Germany.csv) I was not able to process it anymore. 
My issue is coming from some inserted merge texts like "<<<<<< HEAD".
![ex1](https://user-images.githubusercontent.com/72507025/102667065-c87e2500-4188-11eb-86e0-05be7f9b06fe.jpg)

**Comment by timothymodel** [comment]
Thanks for letting us know. I am seeing the same thing that you're seeing. We'll work to identify the source of the problem and resolve it ASAP.

**Comment by timothymodel** [comment]
@AlexHTW, problem should be resolved in the most recent update. Please let me know if you continue to see this issue!

**Comment by timothymodel** [comment]
@AlexHTW, the problem should be resolved in the most recent update. Please let me know if you continue to see this issue!
