### ISSUE TITLE
Error in Saudi Arabia data

### ISSUE THREAD

**Issue by Kexinnnnnnn** [saudiwin/corona_tscs#36]
record id: R_2bPlb0rYpDnRjMzNA  
policy id: 970984
Correct date announced should be 3/25/2020, current data stated as 2/25/2020.

**Comment by IsaacBravo** [comment]
Hi, thank you very much for pointing this out, I have just checked the register of this policy, and the situation remains unchanged. We will contact the Regional Manager to address this situation.
