### ISSUE TITLE
Faulty Downloaded dataset 

### ISSUE THREAD

**Issue by prakashsarnobat** [saudiwin/corona_tscs#44]
[coronanet_release.csv.gz](https://github.com/CoronaNetDataScience/corona_tscs/files/6763867/coronanet_release.csv.gz)

Hello, I am trying to download the core Dataset, but when I actually open the csv file, it ends up being a bunch of jumbled non-standard characters. I am using Windows 10. What has happened? Thanks. Prakash

**Comment by prakashsarnobat** [comment]
I can download individual Countries, but for my work I require all Countries.

**Comment by timothymodel** [comment]
Hi @pradyunramesh, thanks for the question. A csv.gz file is a compressed .csv file that needs to be extracted prior to opening the actual .csv file. See [https://opencsvfile.com/csv-gz-to-csv.html](https://opencsvfile.com/csv-gz-to-csv.html) for more information. If you have Windows, you can use [7-Zip](https://www.7-zip.org/) to extract that file. If you would rather avoid using the compressed file, you might try the .rds version of the dataset.
